### ISSUE TITLE
add installation instructions

### ISSUE THREAD

**Issue by manuelhelmerichs** [wegank/nixos-config#1]
Hi, I'm trying to setup a Parallels NixOS virtual machine (on M1 chip) and came across your work here - sadly I can't seem to figure out how to set it up. Do I need to create a virtual machine first, do I have to install any prerequisites, etc.? I would much appreciate any guidance, thanks :)

**Comment by wegank** [comment]
All you have to do is grab an ISO [here](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.iso_minimal_new_kernel.aarch64-linux), create a VM that boots from it, then follow the [official installation guide](https://nixos.org/manual/nixos/stable/index.html#sec-installation).
