### ISSUE TITLE
大牛对打包dingding有兴趣吗？

### ISSUE THREAD

**Issue by SadSock** [wegank/nixos-config#3]
nixos下还没有人打包ingding，我看到您打包了一个QQ，这两个应该差不多，您可以打包一个dingding吗？

如果我想学习如何打包dingding，我该从哪里开始？

**Comment by wegank** [comment]
> 我看到您打包了一个QQ

QQ 的打包者和维护者是 @fee1-dead。我对 NixOS 下的二进制打包没有什么经验。

> 如果我想学习如何打包dingding，我该从哪里开始？

也许你需要查阅 [Nixpkgs 手册](https://nixos.org/manual/nixpkgs/stable/#chap-quick-start)。

**Comment by SadSock** [comment]
谢谢
